couchbaselabs/node-ottoman

- lib/modelinstance.js
If you are trying to update indexed property with duplicate value, ottoman removes existing refdoc from another document.
> Fix removing existing refdoc from another document on updating document.

- lib/mockstoreadapter.js
- lib/schema.js
- test/indexes.test.js
This patch will simply not create a refdoc index if none of the values are defined. This prevents ottoman from storing "Document|undefined" refdoc keys. If any values are defined, then the index will be created and must be unique. 
Two test cases were added for this, one in which the value is undefined for two otherwise separate documents. The other checks that you can create a refdoc index across multiple fields and that these indices will not collide if they contain the same data in different fields.
> allow undefined fields in refdoc indexes 

- lib/ottoman.js
If a default is set to a falsy value was not taken in account resulting
in undefined. For example {default: 0} was not set on model creation.
This fix this case
> Fix falsy default values

- lib/cbstoreadapter.js
This commit simply makes it possible for the queries that are constructed for n1ql indices to work if they are a boolean value. Someday it might be worth refactoring such that these data types are recognized from the schema instead of the function call but this works for now.
> filters should handle boolean types

- lib/cbstoreadapter.js
- package.json
This appears to be the only major thing I can find that blocks ottoman from being used with couchbase 4.5.0.  Still better test coverage is necessary to be sure, but for me with this change, ottoman runs through all of its tests against a local docker image of couchbase 4.5.0.  Without this change, ottoman fails to run its tests.  The index creation process fails with error messages about indexes already existing, as specified on the github issue.
> Ottoman issue #98; patching index creation for couchbase 4.5.0

- lib/cbstoreadapter.js
Fixes an edge case; when `ensureOttomanIndexes` runs but the user has not specified any indexes, creation process fails because the `indexes` array is empty.  Additionally, the `Ottoman__type` index may not be built.
> fixed missing index in cases where no other n1ql indexes were present

- lib/modelinstance.js
- lib/ottoman.js
- lib/schema.js
- test/model-references.test.js
Via skype discussion, this creates the ability to have models with mixed references, like this:
```
ottoman.model('MixedRefs', { 
aRef: { ref: 'Mixed' },
});
```
Unit tests are added, and adjustments are made to ensure that errors are thrown at serialization time to avoid having any data (integers, strings) put into a mixed reference type.
> support for type { ref: "Mixed" } with associated tests

- lib/modelinstance.js
- package.json
- test/basic.test.js
See this issue for a full discussion: https://github.com/couchbaselabs/node-ottoman/issues/110
> toJSON implementation following Mongoose DBRef pattern, and unit tests

- lib/cbstoreadapter.js
allows Model.find({ key: { $missing: true } }, cb) to find results without the given key
> add $missing to _buildFilterExprs SPECIAL_KEYS for N1QL 'key IS MISSING' queries

- lib/modelinstance.js
- lib/ottoman.js
this follows the same format as used by _findModels, calling _normFilter to replace loaded Models with unloaded references
> update countModels function making options non-required and filters normalised

- lib/cbstoreadapter.js
The bucket name is not being wrapped with ``, causing errors with *all* bucket names. *Edited from: only bucket names with underscores and dashed*
The current #master doesn't seem to work with *any* bucket name. I'm not sure whether couchbase was updated, or what, because this should be causing tests to fail. In my patch-1, `ensureIndices` succeeds with no errors. In the current node-ottoman#master (and 1.0.4 tag), `ensureIndices` is failing from a syntax error during CREATE INDEX.
> Fix for CREATE INDEX query error

- lib/cbstoreadapter.js
Change replace to replace with regex because sometimes index name contains two '::'
> fix creation of GSI indexes

- lib/schema.js
Was running into issues where data would be _an_ object, but would not have the Object prototype, so the instanceof check would fail.
> Fix schema.js instanceof vs typeof

- __test__/query-select.spec.ts
- src/query/helpers/builders.ts
The operator always printed the plain text of the comparator in the N1QL query.
eg
[$or: [{address: {$neq: 100}}, {address: {$neq: 'example'}}]](URL)
Wrong result: **"WHERE address != 100 or address != example"**
Expected result: **"WHERE address != 100 or address != 'example'"**
> fix: Incorrect behavior with operator Not Equals for string

- __test__/schema.complex.types.spec.ts
- __test__/schema.types.spec.ts
- src/schema/helpers/fn-schema.ts
- src/schema/index.ts
- src/schema/interfaces/schema.types.ts
- src/schema/schema.ts
- src/schema/types/array-type.ts
- src/schema/types/boolean-type.ts
- src/schema/types/core-type.ts
- src/schema/types/date-type.ts
- src/schema/types/embed-type.ts
- src/schema/types/index.ts
- src/schema/types/mixed-type.ts
- src/schema/types/number-type.ts
- src/schema/types/reference-type.ts
- src/schema/types/string-type.ts
- src/utils/index.ts
- src/utils/is-type.ts
- vuepress/guides/schema.md
Add support for Mixed Type.
`Mixed` type supports any `Object` types, you can change the value to anything else you like, it can be represented in the following ways:
```ts
const UserSchema = new Schema({
inline: Schema.Types.Mixed,
type: { type: Schema.Types.Mixed, required: true },
any: Object,
other: {},
});
```
> Add Support for Mixed Type and Update Schema Type documentation

- .vscode/launch.json
- __test__/handler-update-many.spec.ts
- src/model/create-model.ts
Fix: https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/15
Set Strategy to THROW in updateById method
> fix: update updateById method to pass Throw Strategy by default

- __test__/query-builder.spec.ts
- __test__/query-select.spec.ts
- src/model/index/n1ql/build-index-query.ts
- src/query/helpers/builders.ts
- src/query/interface/query.types.ts
- vuepress/guides/query-builder.md
To test the clause try this:
```
const filter = {
$any: {
$expr: [{ $in: { search_expr: 'visibility', target_expr: 'network_visibility' } }],
$satisfied: { $in: { search_expr: 'visibility', target_expr: [2] } },
},
};
const result  = model.find(filter);
```
The resulting query must be like:
```sql
SELECT `travel-sample`.* FROM `travel-sample` WHERE ANY visibility IN network_visibility SATISFIES visibility IN [2] END  AND _type="Application"
```
close #426
> test: add test case for ANY X SATISFIES where clause

- __test__/ignore-case.spec.ts
- __test__/schema-inmutable.spec.ts
- src/model/model.ts
- src/query/helpers/builders.ts
- src/query/interface/query.types.ts
- src/query/query.ts
- vuepress/guides/model.md
- vuepress/guides/query-builder.md
How to use:
```ts
User.find({ name: {$eq: 'Jane', $ignoreCase: true }});
// In some cases you need to compare without taking into account case sensitive, for this you can use the $ignoreCase property: true
```
> feat(query): add $ignoreCase property to the query builder where operators

- __test__/query-lean.spec.ts
- src/handler/find/find.ts
- src/model/create-model.ts
Updated findById method, for the lean property. The method must return, the json serialized object of ottoman models, not the SDK respond
> fix(lean): fix issues with lean option in findById method

- vuepress/guides/quick-start.md
PR for quickstart guide. Please note this included rather more code verification and work than our initial remit (e.g "language polishing").
The functionality all looks solid btw! So would be good Dev team to do an additional pass to ensure all the pages and examples are technically correct/up-to-date before Docs team come in to do final polish?
---
Language tweaks, as requested.
But also:
* Simplify bash instructions.
* Fix unspecified imports.
* Changed default user to "Administrator" (in line with usual Couchbase docs)
* Use `example.com` as per https://tools.ietf.org/html/rfc2606
* Fix and simplify async calling:
- add missing `ottoman.start()` call
- move error handling to outer caller, where it gets invoked
instead of hiding messages
- add process.exit, to ensure the script …
> DOC-8129 update quick start guide

- __test__/let-clause.spec.ts
- __test__/schema-timestamps.spec.ts
- src/model/index/n1ql/ensure-n1ql-indexes.ts
- src/ottoman/ottoman.ts
- src/schema/interfaces/schema.types.ts
- src/schema/schema.ts
- vuepress/guides/schema.md
- yarn.lock
adding timestamps as schema option. Also add onIndexCreation event hook to know when all the indexes
were created and ready to use. queryOptions was added for cluster.query method
"feat #531", "feat #532", "feat #542"
> feat(schema): add timestamps as schema option

- __test__/ensure_collections_and_indexes.spec.ts
- src/model/index/n1ql/ensure-n1ql-indexes.ts
- src/ottoman/ottoman.ts
This pull request fixes issue #610 as well as passes all legacy and non legacy tests (without the `OTTOMAN_LEGACY_TEST=1` set).  
Intermittently there would be `LCB_ERR_KEYSPACE_NOT_FOUND` when creating new collections and indexes.  This would happen because sometimes the `ensureCollections` would return before the collections were actually ready.  Additionally sometimes there would be Query `Planning Failures` when running on freshly created models because the `ensureIndexes` would not return the `indexOnlinePromise` unless `indexReadyHooks` were defined.
The changes in this pull request refactor some logic in the `ensureCollections` and `ensureIndexes` functions.  It now guarantees that the collections and the indexes will be ready as described in the documentation.
> Fixes Issue #610

- package.json
Release notes: 
* Bumps `couchbase` dependency to 4.2.0
* This release includes a **major version bump** to the Couchbase dependency, and with it a specific change to handling SSL/TLS connections:
* If you were previously skipping certificate checking with the parameter `?ssl=no_verify` in your connection string, you'll need to update it to `?tls_verify=none`
* More information can be found in [this article](https://developer.couchbase.com/tutorial-nodejs-tls-connection#tls-authentication-without-certificate-checking)
**Full Changelog**: https://github.com/couchbaselabs/node-ottoman/compare/v2.2.2...v2.3.0
> chore(version): bump Ottoman version to 2.3.0 for release

- __test__/handler-update-many.spec.ts
- __test__/model-find-one-and-update.spec.ts
- __test__/model-schema-integration.spec.ts
- src/model/create-model.ts
- src/model/document.ts
> fix: depopulating nested object

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- __test__/fts.spec.ts
- docusaurus/docs/advanced/fts.md
- docusaurus/docusaurus.config.js
- package.json
- src/couchbase.ts
- src/index.ts
- src/ottoman/ottoman.ts
- yarn.lock
> feat: adding full text search support

- __test__/handler-remove-many.spec.ts
- __test__/testData.ts
- __test__/transaction-indexes.spec.ts
- __test__/transactions.spec.ts
- docusaurus/docs/advanced/transactions.md
- docusaurus/docs/basic/ottoman.md
- docusaurus/docs/basic/schema.md
- docusaurus/docusaurus.config.js
- package.json
- src/couchbase.ts
- src/handler/find/find-by-id-options.ts
- src/handler/find/find-options.ts
- src/handler/find/find.ts
- src/handler/remove-many.ts
- src/handler/remove.ts
- src/handler/store.ts
- src/model/create-model.ts
- src/model/document.ts
- src/model/index/refdoc/build-index-refdoc.ts
- src/model/interfaces/find.interface.ts
- src/model/model.ts
- src/model/model.types.ts
- src/model/populate.types.ts
- src/model/utils/model.utils.ts
- src/model/utils/remove-life-cycle.ts
- src/model/utils/store-life-cycle.ts
- src/model/utils/update-refdoc-indexes.ts
- src/ottoman/ottoman.ts
- src/utils/cast-strategy.ts
> Adding transaction support

- src/handler/utils.ts
resolves #790 
Added an artificial delay to `createManyCallback()` to validate:
https://github.com/user-attachments/assets/f3ceb901-9ad9-431d-8fa3-8849316d0f51
<details>
<summary>Code w/ Delay (replace `createManyCallback()` with the below)</summary>
```
export const createManyCallback = (
document: ModelTypes,
metadata: ModelMetadata,
extra: any,
options: saveOptions = {},
): Promise<StatusExecution> => {
const Model = metadata.ottoman.getModel(metadata.modelName);
// Function to introduce a delay
const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
// Artificial delay before calling Model.create
const artificialDelay = 2000; // Delay in milliseconds (e.g., 1000ms = 1 second)
return delay(artificialDelay)
.then(() => Model.create(document, options)) …
```
> Async Batch Processing
