lib/ottoman.js
lib/schema.js
test/basic.test.js

I closed my previous pull request and did some git rebasing in order to squash the commits appropriately and merge with new changes.

Validate for ottoman

---

test/basic.test.js

I added a test for empty default value in order to prevent regressions

Test for falsy default values

---

lib/modelinstance.js
lib/ottoman.js
test/api.test.js
test/instances.test.js
test/plugins.test.js

Main purpose of this PR is to improve basic test coverage for ottoman, and to put a stake in the ground on what looks like most of the public API.   Later refactoring may be needed, and if maintaining backwards compatibility is important, this can't really be assured without some testing.
In doing this testing, found 2 tiny bugs in ottoman and fixed both of them.  Separated this out into different commits.

API Testing

---

lib/mockstoreadapter.js
test/basic.test.js

MockStoreAdapter::get use .cas for CAS value insted of erroneous .key

---

package.json

Kept getting "No repository field error"

fixed repository url metadata

---

lib/cbstoreadapter.js

Replace all instance of "$" in indexName instead of just the first. 

---

lib/cbstoreadapter.js

Added skip to allow proper pagination in n1ql search operation

Added skip to _searchN1qlIndex find call

---

package.json

It would be nice to get this merged in order to update the latest version in NPM. In some environments, it's not possible to npm i via git+https.

Bumped version to get the couchbase dependency update on NPM

---

package-lock.json
package.json

```console
$ npm list cryptiles
ottoman@1.0.5 /path/to/src/github.com/couchbaselabs/node-ottoman
└─┬ couchbase@2.4.6
└─┬ request@2.83.0
└─┬ hawk@6.0.2
└── cryptiles@3.1.2
```

this resolves cryptiles security alert

---

lib/ottoman.js
test/basic.test.js

fix filtering for Dates

---

package.json

Update version number to alpha-3
Update package description

Bump Version to Alpha-3

---

__test__/hooks.spec.ts
__test__/jest.setup.ts
__test__/model-crud.spec.ts
__test__/model-schema-integration.spec.ts
__test__/query-utils.spec.ts
__test__/testData.ts
src/handler/find/find-options.ts
src/handler/find/find.ts
src/handler/store.ts
src/model/create-model.ts
src/model/document.ts
src/model/interfaces/create-model.interface.ts
src/model/interfaces/model-metadata.interface.ts
src/model/utils/store-life-cycle.ts
src/model/utils/update-refdoc-indexes.ts
src/utils/constants.ts
src/utils/populate/exec-populate.ts
src/utils/query/extract-select.ts
vuepress/guides/connections.md
vuepress/guides/model.md
vuepress/guides/schema.md

Also ensure that find and findOne return model instance

fix(customidkey): fix some method to return correct custom idKey

---

__test__/hooks.spec.ts
__test__/indexes-query.spec.ts
__test__/indexes.spec.ts
__test__/model-crud.spec.ts
__test__/model-populate.spec.ts
__test__/model-schema-integration.spec.ts
__test__/testData.ts
jest.config.js
package.json
src/connections/connection-handler.ts
src/connections/connection-manager.ts
src/index.ts
src/model/create-model.ts
src/model/interfaces/create-model.interface.ts
src/model/interfaces/model-metadata.interface.ts
src/schema/helpers/fn-schema.ts
src/schema/schema.ts
src/schema/types/string-type.ts
src/utils/constants.ts
src/utils/populate/can-be-populated.ts
vuepress/guides/first-app.md
vuepress/guides/schema.md

Functions, tests, documentation to support Scopes and Collections in Couchbase Server 6.6 with Developer Preview enabled

V2 sprint 6

---

__test__/model-crud.spec.ts
src/model/create-model.ts
src/model/model.ts
vuepress/guides/document.md
vuepress/guides/model.md

Rename remove method to removeById

---

src/handler/find/find-options.ts
src/utils/search-consistency.ts
vuepress/guides/model.md
vuepress/guides/query-builder.md

fix: documentation issues related with issue 311

---

__test__/handler-remove-many.spec.ts
src/handler/index.ts
src/handler/remove-many.ts
src/handler/types.ts
src/handler/utils.ts
src/model/create-model.ts
src/model/model.ts
vuepress/guides/model.md

feat: Provide removeMany Support

---

__test__/handler-remove-many.spec.ts
__test__/handler-update-many.spec.ts
src/handler/index.ts
src/handler/remove-many.ts
src/handler/types.ts
src/handler/update_many.ts
src/handler/utils.ts
src/model/create-model.ts
src/model/interfaces/update-many.interface.ts
src/model/model.ts
src/types.d.ts
vuepress/guides/model.md

feat(model): provide updateMany Support

---

__test__/model-crud.spec.ts
src/handler/update_many.ts
src/model/create-model.ts
src/model/model.ts
vuepress/guides/document.md
vuepress/guides/model.md
vuepress/guides/schema.md

feat(model): rename update method to updateById

---

__test__/handler-update-many.spec.ts
__test__/model-find-one-and-update.spec.ts
src/model/create-model.ts
src/model/interfaces/find.interface.ts
src/model/model.ts
vuepress/guides/model.md

feat(model): support for findOneAndUpdate

---

__test__/schema-cast.spec.ts
src/model/utils/store-life-cycle.ts

fix(strict): fixing save when strict set to false

---

__test__/create-many.spec.ts
__test__/handler-remove-many.spec.ts
__test__/handler-update-many.spec.ts
src/handler/create-many.ts
src/handler/index.ts
src/handler/remove-many.ts
src/handler/types.ts
src/handler/update_many.ts
src/handler/utils.ts
src/model/create-model.ts
src/model/model.ts
vuepress/guides/model.md

Update bulk operation response and documentations
fix #355

feat(bulk): update bulk operation response errors

---

__test__/model-crud.spec.ts
src/model/create-model.ts
src/model/model.ts
vuepress/guides/model.md

feat(model): rename the replace method to replaceById

---

__test__/model-crud.spec.ts
__test__/utils.spec.ts
src/model/create-model.ts
src/model/document.ts
src/model/interfaces/create-model.interface.ts
src/model/interfaces/model-metadata.interface.ts
src/ottoman/ottoman.ts
src/utils/constants.ts
vuepress/guides/model.md
vuepress/guides/ottoman.md

feat(ottoman): update keyGenerator logic

---

vuepress/guides/first-app.md

minor improvements

---

__test__/ottoman-instances.spec.ts
src/ottoman/ottoman.ts
vuepress/guides/ottoman.md

feat(ottoman): add idKey option at global level

---

__test__/handler-remove-many.spec.ts
__test__/query-select.spec.ts
src/schema/types/array-type.ts
src/schema/types/boolean-type.ts
src/schema/types/core-type.ts
src/schema/types/date-type.ts
src/schema/types/embed-type.ts
src/schema/types/mixed-type.ts
src/schema/types/number-type.ts
src/schema/types/reference-type.ts
src/schema/types/string-type.ts
vuepress/guides/document.md
vuepress/guides/model.md
vuepress/guides/query-builder.md

docs: update documentation related to issue #353

---

.vuepress/config.js
__test__/global-plugin.spec.ts
src/index.ts
src/model/create-model.ts
src/model/model.ts
src/ottoman/ottoman.ts
vuepress/advanced/ottoman.md
vuepress/guides/model.md

"feat #388", "feat #392", "feat #408"

feat: add dropCollection at model level and improve documentation

---

__test__/utils.spec.ts
src/ottoman/ottoman.ts
src/utils/environment-set.ts
src/utils/index.ts
vuepress/guides/ottoman.md

Adding set function for a easier way to set environment variables

feat(global): adding set function

---

.vuepress/config.js
vuepress/advanced/ottoman.md

Update menu link from 'work' to 'works' (plural)
Update links to page from other pages.
Update config route.

Fix "How Ottoman Works" menu/button/links (plural)

---

__test__/model-crud.spec.ts
__test__/model-populate.spec.ts
src/model/create-model.ts

fix: update findOne to return DocumentNotFoundError

---

__test__/model-crud.spec.ts
__test__/utils.spec.ts
package.json
src/exceptions/ottoman-errors.ts
src/model/create-model.ts
src/model/document.ts
src/model/interfaces/create-model.interface.ts
src/model/interfaces/model-metadata.interface.ts
src/ottoman/ottoman.ts
src/utils/constants.ts
vuepress/guides/model.md
vuepress/guides/ottoman.md
yarn.lock

feat(ottoman): allow key-generator delimiter configurable

---

__test__/global-plugin.spec.ts
__test__/model-crud.spec.ts
__test__/model-find-one-and-update.spec.ts
__test__/schema-inmutable.spec.ts
src/model/create-model.ts
src/model/document.ts
src/model/model.ts
src/model/model.types.ts
src/ottoman/ottoman.ts
src/query/interface/query.types.ts
src/utils/is-model.ts
src/utils/pipe.ts
vuepress/guides/schema.md

Also fix multiples hooks execution and update default index documentation
"feat #333"

feat(model): adding generics

---

__test__/create-many.spec.ts
__test__/handler-remove-many.spec.ts
__test__/handler-update-many.spec.ts
__test__/model-crud.spec.ts
__test__/schema-inmutable.spec.ts
src/handler/create-many.ts
src/handler/types.ts
src/handler/update_many.ts
src/handler/utils.ts
src/model/create-model.ts
src/model/model.ts
src/model/model.types.ts
src/ottoman/ottoman.ts

"feat #4467", "fix #475", "fix #466", "fix #476", "fix #452", "feat #461"

feat(model): export and extend model funcionalities

---

src/index.ts

fix(model): export ModelOptions interface

---

src/handler/create-many.ts
src/handler/types.ts
src/handler/utils.ts
src/model/model.ts

feat(model): add generics to bulk operation's response

---

__test__/model-crud.spec.ts
__test__/schema.add.spec.ts
__test__/schema.types.spec.ts
src/model/create-model.ts
src/model/index/n1ql/ensure-n1ql-indexes.ts
src/model/model.ts
src/ottoman/ottoman.ts
src/schema/types/string-type.ts

Also remove countOptions, fix stringType to handle null
"feat #499", "fix #502", "fix #508"

feat(ottoman): retry create scopes and collections

---

src/handler/find/find.ts
src/utils/constants.ts
vuepress/guides/model.md
vuepress/guides/ottoman.md

Also print in console the N1QL queries executed in Ottoman when it's in debug mode
"fix #513", "feat #509"

fix(ttl): setting correct default value for maxExpiry

---

src/handler/find/find-options.ts

fix(find): update IFindOptions with the current populate type

---

__test__/schema-inmutable.spec.ts
src/handler/find/find.ts
src/model/create-model.ts
src/model/document.ts
vuepress/guides/schema.md

Update immutable's documentation

feat(immutable): can modify immutable properties if the document's `isNew` property is false

---

__test__/create-many.spec.ts
__test__/handler-update-many.spec.ts
src/handler/create-many.ts
src/handler/remove-many.ts
src/handler/update_many.ts
src/handler/utils.ts
src/index.ts
src/model/create-model.ts
src/model/document.ts
src/model/interfaces/find.interface.ts
src/model/model.ts
src/model/model.types.ts
src/utils/cast-strategy.ts

Only available for KV operations

feat(ttl): leverage maxExpiry use in ottoman from couchbase

---

.github/workflows/main.yml
.github/workflows/pull_request.yml
__test__/schema-timestamps.spec.ts
src/model/index/n1ql/ensure-n1ql-indexes.ts
src/model/utils/update-refdoc-indexes.ts
src/ottoman/ottoman.ts
src/query/helpers/builders.ts
src/utils/populate/can-be-populated.ts

remove github actions test for now, remove query logic in the from clause

fix(test): remove test script from CI

---

vuepress/guides/schema.md

https://issues.couchbase.com/browse/DOC-8129

Minor doc tidy up.

---

README.md
__test__/jest.setup.ts
__test__/model-crud.spec.ts
__test__/ottoman-instances.spec.ts
__test__/server-ops.spec-broken.ts
package.json
src/index.ts
src/model/create-model.ts
src/ottoman/ottoman.ts
src/query/query.ts
src/schema/index.ts
vuepress/.vuepress/config.js
vuepress/guides/faq.md
vuepress/guides/model.md
vuepress/guides/ottoman-couchbase.md
vuepress/guides/ottoman.md
vuepress/guides/query-builder.md
vuepress/guides/schema.md
yarn.lock

Update Ottoman instances to be handle by unique UUID. Also, fix some broken links in the documentation

feat(couchbase): update to couchbase 3.2.1

---

__test__/query-lean.spec.ts
src/model/utils/model.utils.ts
vuepress/guides/model.md

feat(i-539): return document id ref if not exist

---

package.json
yarn.lock

Bump Couchbase Package to 3.2.3

---

.github/workflows/pull_request.yml

workflow test

---

__test__/global-plugin.spec.ts
__test__/model-crud.spec.ts
__test__/model-find-projection.spec.ts
src/handler/find/find.ts
src/ottoman/ottoman.ts

find method now return _type field by default, also now delimiter can take an empty string ("") as value

fix(model): fix model inconsistency in find method

---

.github/workflows/main.yml
.github/workflows/pull_request.yml
__test__/ensure_collections_and_indexes.spec.ts
__test__/global-plugin.spec.ts
__test__/nested-model-key.spec.ts
__test__/testData.ts
__test__/utils.spec.ts
src/handler/find/find.ts
src/model/create-model.ts
src/model/document.ts
src/model/index/n1ql/ensure-n1ql-indexes.ts
src/utils/getValueByPath.ts
src/utils/index.ts
src/utils/setValueByPath.ts

feat(ottoman): add support for nested modelKey

---

__test__/schema-inmutable.spec.ts
__test__/schema-timestamps.spec.ts
__test__/testData.ts
__test__/utils.spec.ts
package.json
src/model/create-model.ts
src/model/document.ts
src/model/hooks/exec-hooks.ts
src/utils/getValueByPath.ts
src/utils/setValueByPath.ts
yarn.lock

add lodash library
enhance update and replace nested assign

feat(hooks): trigger embed schema hooks

---

.github/workflows/issue.yaml
.github/workflows/send_issue.sh

Automate sending issue to slack channel in case a new issue is opened. Creating a PR to merge to main as issue trigger can be tested only on the default branch.

Devadv 2257 issue

---

__test__/schema-cast.spec.ts
src/schema/helpers/fn-schema.ts
src/schema/types/array-type.ts

fix(schema): set correct options for ArrayType

---

docusaurus/docs/advanced/ottoman-couchbase.md
docusaurus/docs/basic/schema.md
docusaurus/docusaurus.config.js
docusaurus/package.json
docusaurus/yarn.lock
src/index.ts

docusaurus version was upgrade to 2.4.1
got and trim dependencies were removed

fix: vulnerabilities in docs project

---

README.md
docusaurus/docs/advanced/sdk-comparison.md
docusaurus/docs/quick-start.md

docs: update docs information

---

README.md
docusaurus/docs/intro.md

docs: fix broken links on intro page
